name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20'
      - name: Set up service account
        env:
          SECRET: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: base64 -d <<< $SECRET > service_account_key.json
      - name: Run tests
        env:
          KMS_KEYSPEC: projects/keymaster-301315/locations/global/keyRings/github/cryptoKeys/testing
          GOOGLE_APPLICATION_CREDENTIALS: ./service_account_key.json
        run: go test -cover .
